### PR TITLE
docs: remove PR checklist from template

### PR DESCRIPTION
**Pull request by DarylLyonsLF**
## Remove PR Checklist

The PR checklist has been in use for a while now. I feel that it doesn't quite hit the mark with it's intention and ~~is mostly more of an annoyance than anything~~ can often lead to confusion as the items are rarely all relevant which leads to developers having seemingly not done something they "should have"  .

I'd love to hear if anyone is seeing any benefit from this list and more than happy to leave it in if so.

### Updates
* Remove checklist from PR template 2c0325a6a0bb7d70da274ac9e40ec54cf3a0a40d

---

Case in point.... 😄 

- [ ] Package dependencies have been updated (where possible)
- [ ] Documentation has been updated
- [ ] Automated tests have been updated

### CODE REVIEW

**Review by Rudolf-LF — COMMENTED** [review]
I would not say an annoyance.  It has some points that we need to be aware of.  We should always ask if the relevant documentation has been updated when looking at a PR.  Unit tests should reflect business AC and should not just be changed to make the tests pass.  Anyone should feel free to challenge any changes in unit tests - especially where a unit test is against an external(from the service) interface.  Another good habit may be running 'npm audit fix' before starting new work.

Short answer is, I don't mind taking it out.  It should become a habit to do these things and question whether someone else has done it.

**Review by RaquelABermejo — COMMENTED** [review]
I find the list useful to remember some PR review parts but as Rudolf said we just need to get the habit and as Daryl said this list is not always adequate based on the type to repo.
I don't main if you remove it but can the package dependencies and documentation update be included into [Code Review Checklist](https://leadforensics.atlassian.net/wiki/spaces/EN/pages/289341443/Code+Review+Checklist) article?

**Review by viktalf — COMMENTED** [review]
I find the checklist useful as there are multiple times I've forgotten to update the readme, and I just delete the bits that aren't relevant when creating a PR. Also, as per Raquel's comment, for this PR you could have ticked 'Documentation has been updated', linked to the updated Confluence page and removed/striked through the other items.
I think there may be a departmental cultural issue which removing the checklist may make worse, especially given we're all pushed for time.

**Comment by RaquelABermejo** [comment]
> I find the checklist useful as there are multiple times I've forgotten to update the readme, and I just delete the bits that aren't relevant when creating a PR. Also, as per Raquel's comment, for this PR you could have ticked 'Documentation has been updated', linked to the updated Confluence page and removed/striked through the other items. I think there may be a departmental cultural issue which removing the checklist may make worse, especially given we're all pushed for time.

I have the same concern as @viktalf because, in my opinion, the list have proved to be useful multiple times before, on the teams that I worked before. @DarylLyonsLF Maybe we can vote this in the engineering channel, so we can see dev's opinions as final users.

**Comment by DarylLyonsLF** [comment]
Alright, I'll close down this PR. Thanks for the feedback all 😃.

**Pull request closed without merging**
